### ISSUE TITLE
Plot single x column with multiple y column

### ISSUE THREAD

**Issue by hiztirab** [jennybc/ggplot2-tutorial#2]
If we use +geom_point command to add extra layer on a plot then how we can add states and lables in each case?

**Comment by jennybc** [comment]
ggplot2 only supports a secondary y axis in a very narrow scenario: basically you can only have one y axis or scale but you can label them with different units. Example: display miles on left, km on right or ditto for fahrenheit and Celsius.

Otherwise, if I understand you, you need to reshape your data and use groups (one group per pre-reshaping "y column") or add points via multiple layers (one layer per column).
